<template><section class="discovery-panel exporter-panel"><header><div><h2>node_exporter 一键管理</h2><span>通过 SSH 批量安装、升级或卸载，并由网关下发官方二进制，支持自定义端口</span></div><button @click="load"><RefreshCw :class="{spin:loading}"/>刷新</button></header><div class="exporter-summary"><article><RadioTower/><span>当前版本<strong>v{{version||'-'}}</strong></span></article><article><ShieldCheck/><span>下载通道<strong>网关内网下发</strong></span></article><article><Activity/><span>托管方式<strong>systemd</strong></span></article></div><div class="scanner-form exporter-form"><label><span>目标主机（每行一个 IP）</span><textarea v-model="hosts" rows="4"></textarea></label><label><span>SSH 端口</span><input v-model.number="sshPort" type="number" min="1" max="65535"></label><label><span>node_exporter 端口</span><input v-model.number="exporterPort" type="number" min="1" max="65535"></label><label><span>网关地址（安装源）</span><input v-model="gatewayUrl" placeholder="http://172.28.69.161:30080"></label><label><span>SSH 凭据</span><select v-model="credentialId"><option value="">使用服务端默认</option><option v-for="credential in credentials" :key="credential.id" :value="credential.id">{{credential.name}} ({{credential.username||'-'}})</option></select></label><div class="exporter-actions"><button class="primary" :disabled="busy" @click="install">安装 / 升级</button><button class="danger" :disabled="busy" @click="uninstall">卸载</button></div></div><div v-if="error" class="discovery-error exporter-error">{{error}}</div><div v-if="results.length" class="exporter-results"><article v-for="item in results" :key="item.host" :class="{ok:item.ok}"><strong>{{item.host}}</strong><b>{{item.ok?'成功':'失败'}}</b><span>{{item.info}}</span></article></div></section></template>

<script setup lang="ts">
import { computed,onMounted,ref } from 'vue'
import { Activity,RadioTower,RefreshCw,ShieldCheck } from 'lucide-vue-next'
import { listCredentials,type Credential } from '@/api/cmdb'
import { useAuthStore } from '@/stores/useAuthStore'
type Result={host:string;ok:boolean;info:string;port?:number}
const auth=useAuthStore(),hosts=ref('172.28.69.161'),sshPort=ref(22),exporterPort=ref(9100),gatewayUrl=ref('http://172.28.69.161:30080'),credentialId=ref(''),credentials=ref<Credential[]>([]),version=ref(''),busy=ref(false),loading=ref(false),error=ref(''),results=ref<Result[]>([])
const headers=computed(()=>({Authorization:`Bearer ${auth.token}`,'Content-Type':'application/json'}));async function request<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:headers.value});if(!response.ok){let message=`请求失败 (${response.status})`;try{const body=await response.json() as {message?:string};message=body.message||message}catch{}throw new Error(message)}return response.json() as Promise<T>}
async function load(){loading.value=true;try{[credentials.value,version.value]=await Promise.all([listCredentials(auth.token),request<{version:string}>('/api/v1/agent/install/node-exporter/version').then(v=>v.version)]);error.value=''}catch(reason){error.value=reason instanceof Error?reason.message:'Exporter 信息加载失败'}finally{loading.value=false}}
function targetHosts(){return hosts.value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean)}
async function install(){busy.value=true;error.value='';results.value=[];try{results.value=await request<Result[]>('/api/v1/discovery/exporter-install',{method:'POST',body:JSON.stringify({hosts:targetHosts(),port:sshPort.value,exporterPort:exporterPort.value,gatewayUrl:gatewayUrl.value,credentialId:credentialId.value})})}catch(reason){error.value=reason instanceof Error?reason.message:'安装失败'}finally{busy.value=false}}
async function uninstall(){busy.value=true;error.value='';results.value=[];try{results.value=await request<Result[]>('/api/v1/discovery/exporter-uninstall',{method:'POST',body:JSON.stringify({hosts:targetHosts(),port:sshPort.value,credentialId:credentialId.value})})}catch(reason){error.value=reason instanceof Error?reason.message:'卸载失败'}finally{busy.value=false}}
onMounted(load)
</script>

<style scoped>
.exporter-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;padding:18px 20px}.exporter-summary article{display:flex;align-items:center;gap:12px;padding:14px;border:1px solid #18384a;border-radius:10px;background:#091b29}.exporter-summary svg{color:#22d3ee}.exporter-summary span{display:flex;flex-direction:column;color:#7890aa;font-size:12px}.exporter-summary strong{color:#e5f4ff;font-size:15px;margin-top:4px}.exporter-form{grid-template-columns:minmax(260px,1fr) 140px 160px minmax(220px,.8fr) minmax(220px,.8fr) auto!important}.exporter-actions{display:flex;gap:8px;align-items:end}.exporter-error{margin:0 20px 14px}.exporter-results{display:grid;gap:8px;padding:0 20px 20px}.exporter-results article{display:grid;grid-template-columns:160px 70px 1fr;gap:10px;padding:11px 13px;border:1px solid #5b2230;border-radius:8px;background:#2d121a}.exporter-results article.ok{border-color:#155e75;background:#082b38}.exporter-results b{color:#fb7185}.exporter-results article.ok b{color:#2dd4bf}.exporter-results span{color:#91adbd;word-break:break-all}@media(max-width:1100px){.exporter-summary{grid-template-columns:1fr}.exporter-form{grid-template-columns:1fr!important}.exporter-actions{flex-direction:column;align-items:stretch}.exporter-results article{grid-template-columns:1fr}}
</style>

