<script setup lang="ts">
import{computed,onMounted,onUnmounted,ref}from'vue'
import{useRoute}from'vue-router'
import{CalendarClock,CheckCircle2,Clock3,FilePlus2,Play,RefreshCw,RotateCcw,ScrollText,ShieldCheck,Square,Terminal,Workflow,X}from'lucide-vue-next'
import{useAuthStore}from'@/stores/useAuthStore'
import{progressTone,statusLabel}from'@/features/jobs/jobsModel'
import type{Asset}from'@/features/cmdb/types'
import{createExecution,createTemplate,fetchJobAssets,fetchJobData,jobAction,toggleTemplate,type Job,type Schedule,type Summary,type Template}from'@/api/jobs'

const auth=useAuthStore(),templates=ref<Template[]>([]),jobs=ref<Job[]>([]),schedules=ref<Schedule[]>([]),assets=ref<Asset[]>([]),summary=ref<Summary>(),selected=ref<Job>(),tab=ref<'executions'|'schedules'>('executions'),loading=ref(false),error=ref('')
const route=useRoute()
const showTemplate=ref(false),showExecute=ref(false),activeTemplate=ref<Template>(),selectedTargets=ref<string[]>([]),timeoutSeconds=ref(300)
const templateForm=ref({name:'',category:'巡检',description:'',command:'',risk:'low' as 'low'|'medium'|'high'})
const onlineAssets=computed(()=>assets.value.filter(item=>item.status!=='offline'))
async function load(){loading.value=true;error.value='';try{const selectedId=selected.value?.id||(typeof route.query.job==='string'?route.query.job:'');[summary.value,templates.value,jobs.value,schedules.value]=await fetchJobData(auth.token);if(selectedId)selected.value=jobs.value.find(item=>item.id===selectedId)}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
async function openExecution(template:Template){activeTemplate.value=template;selectedTargets.value=[];showExecute.value=true;if(!assets.value.length){try{assets.value=(await fetchJobAssets(auth.token)).data}catch(e){error.value=e instanceof Error?e.message:'资产加载失败'}}}
async function submitExecution(){if(!activeTemplate.value||!selectedTargets.value.length)return;try{let job=await createExecution(auth.token,{templateId:activeTemplate.value.id,targets:selectedTargets.value,timeoutSeconds:timeoutSeconds.value});if(job.status==='pending')job=await jobAction(auth.token,job.id,'run');showExecute.value=false;await load();selected.value=jobs.value.find(item=>item.id===job.id)}catch(e){error.value=e instanceof Error?e.message:'创建任务失败'}}
async function submitTemplate(){try{await createTemplate(auth.token,templateForm.value);showTemplate.value=false;templateForm.value={name:'',category:'巡检',description:'',command:'',risk:'low'};await load()}catch(e){error.value=e instanceof Error?e.message:'模板保存失败'}}
async function toggle(item:Template){try{await toggleTemplate(auth.token,item.id);await load()}catch(e){error.value=e instanceof Error?e.message:'操作失败'}}
async function action(job:Job,type:'run'|'retry'|'cancel'|'approve'){try{await jobAction(auth.token,job.id,type);await load();selected.value=jobs.value.find(item=>item.id===job.id)}catch(e){error.value=e instanceof Error?e.message:'操作失败'}}
let timer:number;onMounted(()=>{load();timer=window.setInterval(()=>{if(jobs.value.some(item=>item.status==='running'))load()},1000)});onUnmounted(()=>window.clearInterval(timer))
</script>

<template><section class="jobs-page">
  <header class="jobs-heading"><div><span>AUTOMATION CONTROL PLANE</span><h1>自动化任务中心</h1><p>标准化作业、CMDB目标选择、安全审批与全程审计</p></div><div class="heading-actions"><button @click="showTemplate=true"><FilePlus2/>新建模板</button><button @click="load"><RefreshCw :class="{spin:loading}"/>刷新</button></div></header>
  <div v-if="error" class="jobs-error">{{error}}<button @click="error=''">关闭</button></div>
  <div class="jobs-summary"><article><Workflow/><span>作业模板<strong>{{summary?.templates}}</strong></span></article><article><Clock3/><span>执行中<strong>{{summary?.running}}</strong></span></article><article><CheckCircle2/><span>今日成功<strong>{{summary?.successToday}}</strong></span></article><article><RotateCcw/><span>今日失败<strong>{{summary?.failedToday}}</strong></span></article><article><CalendarClock/><span>调度计划<strong>{{summary?.schedules}}</strong></span></article></div>
  <section class="template-strip"><header><h2>作业模板</h2><span>高风险模板执行前必须由其他管理员审批</span></header><div><article v-for="item in templates" :key="item.id" :class="{disabled:!item.enabled}"><b :data-risk="item.risk">{{item.category}} · {{item.risk}}</b><h3>{{item.name}}</h3><p>{{item.description}}</p><code>{{item.command}}</code><footer><button class="subtle" @click="toggle(item)">{{item.enabled?'停用':'启用'}}</button><button :disabled="!item.enabled" @click="openExecution(item)"><Play/>选择目标</button></footer></article></div></section>
  <div class="jobs-workspace"><main><nav><button :class="{active:tab==='executions'}" @click="tab='executions'">执行记录</button><button :class="{active:tab==='schedules'}" @click="tab='schedules'">调度计划</button></nav><template v-if="tab==='executions'"><button v-for="job in jobs" :key="job.id" class="job-entry" :class="{selected:selected?.id===job.id}" @click="selected=job"><b :data-status="job.status">{{statusLabel(job.status)}}</b><div><strong>{{job.name}}</strong><span>{{job.targets.join('、')}} · {{job.operator}}</span></div><div class="entry-progress"><i :data-tone="progressTone(job.status)" :style="{width:job.progress+'%'}"></i></div><em>{{job.progress}}%</em><time>{{job.startedAt.slice(11)}}</time></button></template><template v-else><article v-for="schedule in schedules" :key="schedule.id" class="schedule-entry"><CalendarClock/><div><strong>{{schedule.name}}</strong><span>{{schedule.cron}}</span></div><time>下次 {{schedule.nextRun}}</time><b>{{schedule.enabled?'已启用':'已停用'}}</b></article></template></main>
    <aside class="job-console"><template v-if="selected"><header><div><span>EXECUTION LOG</span><h2>{{selected.name}}</h2></div><Terminal/></header><div class="console-meta"><span>{{selected.id}}</span><span>第 {{selected.attempt}} 次</span><b :data-status="selected.status">{{statusLabel(selected.status)}}</b></div><div class="approval-note" v-if="selected.status==='awaiting_approval'">高风险任务等待审批，申请人 {{selected.operator}} 不能自审。</div><div class="log-stream"><p v-for="log in selected.logs" :key="log.time+log.message" :data-level="log.level"><time>{{log.time}}</time><b>[{{log.level}}]</b>{{log.message}}</p></div><footer><button v-if="selected.status==='awaiting_approval'" @click="action(selected,'approve')"><ShieldCheck/>审批通过</button><button v-if="selected.status==='pending'" @click="action(selected,'run')"><Play/>开始执行</button><button v-if="selected.status==='running'" @click="action(selected,'cancel')"><Square/>取消执行</button><button v-if="selected.status==='failed'||selected.status==='cancelled'" @click="action(selected,'retry')"><RotateCcw/>重新执行</button></footer></template><div v-else class="empty-console"><ScrollText/><strong>选择执行记录</strong><span>查看实时输出与审计日志</span></div></aside>
  </div>
  <div v-if="showTemplate" class="job-modal" @click.self="showTemplate=false"><form @submit.prevent="submitTemplate"><header><h2>新建作业模板</h2><button type="button" @click="showTemplate=false"><X/></button></header><label>模板名称<input v-model="templateForm.name" required maxlength="80"></label><label>分类<input v-model="templateForm.category" required maxlength="30"></label><label>描述<textarea v-model="templateForm.description" maxlength="300"></textarea></label><label>受控命令<input v-model="templateForm.command" required maxlength="500" placeholder="例如 health-check --full"></label><label>风险等级<select v-model="templateForm.risk"><option value="low">低风险</option><option value="medium">中风险</option><option value="high">高风险（需要审批）</option></select></label><footer><button type="button" @click="showTemplate=false">取消</button><button>保存模板</button></footer></form></div>
  <div v-if="showExecute&&activeTemplate" class="job-modal" @click.self="showExecute=false"><form class="target-dialog" @submit.prevent="submitExecution"><header><div><small>CREATE EXECUTION</small><h2>{{activeTemplate.name}}</h2></div><button type="button" @click="showExecute=false"><X/></button></header><label>执行超时（秒）<input v-model.number="timeoutSeconds" type="number" min="10" max="86400"></label><h3>选择CMDB目标资产 <span>已选 {{selectedTargets.length}} 台</span></h3><div class="target-list"><label v-for="asset in onlineAssets" :key="asset.id"><input v-model="selectedTargets" type="checkbox" :value="asset.id"><div><strong>{{asset.name}}</strong><span>{{asset.ip||asset.id}} · {{asset.environment}} · {{asset.projectGroup}}</span></div><b>{{asset.status}}</b></label></div><footer><button type="button" @click="showExecute=false">取消</button><button :disabled="!selectedTargets.length"><Play/>创建并执行</button></footer></form></div>
</section></template>
