<script setup lang="ts">
import{computed,onMounted,onUnmounted,ref}from'vue'
import{useRoute}from'vue-router'
import{CalendarClock,CalendarPlus,CheckCircle2,Clock3,FilePlus2,Pencil,Play,RefreshCw,RotateCcw,ScrollText,ShieldCheck,Square,Terminal,Trash2,Workflow,X,Zap}from'lucide-vue-next'
import{useAuthStore}from'@/stores/useAuthStore'
import{progressTone,statusLabel}from'@/features/jobs/jobsModel'
import type{Asset}from'@/features/cmdb/types'
import{createExecution,createPlaybook,createPlaybookExecution,createSchedule,createTemplate,deletePlaybook,deleteSchedule,fetchJobAssets,fetchJobData,jobAction,runSchedule,togglePlaybook,toggleSchedule,toggleTemplate,updatePlaybook,updateSchedule,type Job,type Playbook,type PlaybookInput,type Schedule,type ScheduleInput,type Summary,type Template}from'@/api/jobs'

const auth=useAuthStore(),templates=ref<Template[]>([]),jobs=ref<Job[]>([]),schedules=ref<Schedule[]>([]),assets=ref<Asset[]>([]),summary=ref<Summary>(),selected=ref<Job>(),tab=ref<'executions'|'schedules'>('executions'),loading=ref(false),error=ref('')
const route=useRoute()
const showTemplate=ref(false),showExecute=ref(false),activeTemplate=ref<Template>(),selectedTargets=ref<string[]>([]),timeoutSeconds=ref(300)
const templateForm=ref({name:'',category:'巡检',description:'',command:'',risk:'low' as 'low'|'medium'|'high'})
const showSchedule=ref(false),editingSchedule=ref<Schedule>(),scheduleSaving=ref(false),scheduleForm=ref<ScheduleInput>({name:'',templateId:'',targets:[],cron:'0 2 * * *',timeoutSeconds:300,enabled:true})
const cronPresets=[{label:'每小时',value:'0 * * * *'},{label:'每天 02:00',value:'0 2 * * *'},{label:'每周日 03:00',value:'0 3 * * 0'},{label:'每月 1 日 04:00',value:'0 4 1 * *'}]
const playbooks=ref<Playbook[]>([]),showPlaybook=ref(false),editingPlaybook=ref<Playbook>(),playbookSaving=ref(false),activePlaybook=ref<Playbook>(),executionVariables=ref<Record<string,string>>({})
const playbookForm=ref<PlaybookInput & {id:string}>({id:'',name:'',description:'',content:'',constants:{},variables:{},enabled:true})
const constantsText=ref(''),variablesText=ref('')
const onlineAssets=computed(()=>assets.value.filter(item=>item.status!=='offline'))
async function load(){loading.value=true;error.value='';try{const selectedId=selected.value?.id||(typeof route.query.job==='string'?route.query.job:'');[summary.value,templates.value,jobs.value,schedules.value,playbooks.value]=await fetchJobData(auth.token);if(selectedId)selected.value=jobs.value.find(item=>item.id===selectedId)}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
async function openExecution(template:Template){activeTemplate.value=template;selectedTargets.value=[];showExecute.value=true;if(!assets.value.length){try{assets.value=(await fetchJobAssets(auth.token)).data}catch(e){error.value=e instanceof Error?e.message:'资产加载失败'}}}
async function submitExecution(){if((!activeTemplate.value&&!activePlaybook.value)||!selectedTargets.value.length)return;try{let job;if(activePlaybook.value)job=await createPlaybookExecution(auth.token,{playbookId:activePlaybook.value.id,targets:selectedTargets.value,variables:executionVariables.value,timeoutSeconds:timeoutSeconds.value});else job=await createExecution(auth.token,{templateId:activeTemplate.value!.id,targets:selectedTargets.value,timeoutSeconds:timeoutSeconds.value});if(job.status==='pending')job=await jobAction(auth.token,job.id,'run');showExecute.value=false;await load();selected.value=jobs.value.find(item=>item.id===job.id)}catch(e){error.value=e instanceof Error?e.message:'创建任务失败'}}
async function submitTemplate(){try{await createTemplate(auth.token,templateForm.value);showTemplate.value=false;templateForm.value={name:'',category:'巡检',description:'',command:'',risk:'low'};await load()}catch(e){error.value=e instanceof Error?e.message:'模板保存失败'}}
async function toggle(item:Template){try{await toggleTemplate(auth.token,item.id);await load()}catch(e){error.value=e instanceof Error?e.message:'操作失败'}}
async function ensureAssets(){if(!assets.value.length){try{assets.value=(await fetchJobAssets(auth.token)).data}catch(e){error.value=e instanceof Error?e.message:'资产加载失败'}}}
async function openCreateSchedule(){await ensureAssets();editingSchedule.value=undefined;scheduleForm.value={name:'',templateId:templates.value.find(item=>item.enabled)?.id||'',targets:[],cron:'0 2 * * *',timeoutSeconds:300,enabled:true};showSchedule.value=true;error.value=''}
async function openEditSchedule(item:Schedule){await ensureAssets();editingSchedule.value=item;scheduleForm.value={name:item.name,templateId:item.templateId,targets:[...item.targets],cron:item.cron,timeoutSeconds:item.timeoutSeconds,enabled:item.enabled};showSchedule.value=true;error.value=''}
async function submitSchedule(){if(!scheduleForm.value.name.trim()||!scheduleForm.value.templateId||!scheduleForm.value.cron.trim()||!scheduleForm.value.targets.length){error.value='请填写计划名称、作业模板、Cron 表达式并选择目标资产';return}scheduleSaving.value=true;try{if(editingSchedule.value)await updateSchedule(auth.token,editingSchedule.value.id,scheduleForm.value);else await createSchedule(auth.token,scheduleForm.value);showSchedule.value=false;await load()}catch(e){error.value=e instanceof Error?e.message:'计划保存失败'}finally{scheduleSaving.value=false}}
async function toggleScheduleItem(item:Schedule){try{await toggleSchedule(auth.token,item.id);await load()}catch(e){error.value=e instanceof Error?e.message:'计划状态更新失败'}}
async function runScheduleNow(item:Schedule){try{const job=await runSchedule(auth.token,item.id);await load();selected.value=jobs.value.find(value=>value.id===job.id);tab.value='executions'}catch(e){error.value=e instanceof Error?e.message:'立即执行失败'}}
async function removeScheduleItem(item:Schedule){if(!window.confirm(`确定删除计划“${item.name}”吗？`))return;try{await deleteSchedule(auth.token,item.id);await load()}catch(e){error.value=e instanceof Error?e.message:'计划删除失败'}}
function parseKeyValues(value:string){const out:Record<string,string>={};value.split(/\r?\n/).forEach(line=>{const index=line.indexOf('=');if(index<=0)return;const key=line.slice(0,index).trim();const text=line.slice(index+1).trim();if(key)out[key]=text});return out}
function mapToText(value?:Record<string,string>){return value?Object.entries(value).map(([key,text])=>`${key}=${text}`).join('\n'):''}
function openCreatePlaybook(){editingPlaybook.value=undefined;playbookForm.value={id:'',name:'',description:'',content:'',constants:{},variables:{},enabled:true};constantsText.value='';variablesText.value='';showPlaybook.value=true;error.value=''}
function editPlaybook(item:Playbook){editingPlaybook.value=item;playbookForm.value={id:item.id,name:item.name,description:item.description,content:item.content,constants:{...item.constants},variables:{...item.variables},enabled:item.enabled};constantsText.value=mapToText(item.constants);variablesText.value=mapToText(item.variables);showPlaybook.value=true;error.value=''}
async function submitPlaybook(){playbookForm.value.constants=parseKeyValues(constantsText.value);playbookForm.value.variables=parseKeyValues(variablesText.value);if(!playbookForm.value.name.trim()||!playbookForm.value.content.trim()){error.value='Playbook 名称和内容不能为空';return}playbookSaving.value=true;try{if(editingPlaybook.value)await updatePlaybook(auth.token,editingPlaybook.value.id,playbookForm.value);else await createPlaybook(auth.token,playbookForm.value);showPlaybook.value=false;await load()}catch(e){error.value=e instanceof Error?e.message:'Playbook 保存失败'}finally{playbookSaving.value=false}}
async function togglePlaybookItem(item:Playbook){try{await togglePlaybook(auth.token,item.id);await load()}catch(e){error.value=e instanceof Error?e.message:'Playbook 状态更新失败'}}
async function removePlaybookItem(item:Playbook){if(!window.confirm(`确定删除 Playbook“${item.name}”吗？`))return;try{await deletePlaybook(auth.token,item.id);await load()}catch(e){error.value=e instanceof Error?e.message:'Playbook 删除失败'}}
async function openPlaybookExecution(item:Playbook){await ensureAssets();activeTemplate.value=undefined;activePlaybook.value=item;executionVariables.value={...item.variables};selectedTargets.value=[];showExecute.value=true}
async function action(job:Job,type:'run'|'retry'|'cancel'|'approve'){try{await jobAction(auth.token,job.id,type);await load();selected.value=jobs.value.find(item=>item.id===job.id)}catch(e){error.value=e instanceof Error?e.message:'操作失败'}}
let timer:number,scheduleTimer:number;onMounted(()=>{load();timer=window.setInterval(()=>{if(jobs.value.some(item=>item.status==='running'))load()},1000);scheduleTimer=window.setInterval(()=>{if(schedules.value.some(item=>item.enabled))load()},30000)});onUnmounted(()=>{window.clearInterval(timer);window.clearInterval(scheduleTimer)})
</script>

<template><section class="jobs-page">
  <header class="jobs-heading"><div><span>AUTOMATION CONTROL PLANE</span><h1>自动化任务中心</h1><p>标准化作业、CMDB目标选择、安全审批与全程审计</p></div><div class="heading-actions"><button @click="showTemplate=true"><FilePlus2/>新建模板</button><button @click="load"><RefreshCw :class="{spin:loading}"/>刷新</button></div></header>
  <div v-if="error" class="jobs-error">{{error}}<button @click="error=''">关闭</button></div>
  <div class="jobs-summary"><article><Workflow/><span>作业模板<strong>{{summary?.templates}}</strong></span></article><article><Clock3/><span>执行中<strong>{{summary?.running}}</strong></span></article><article><CheckCircle2/><span>今日成功<strong>{{summary?.successToday}}</strong></span></article><article><RotateCcw/><span>今日失败<strong>{{summary?.failedToday}}</strong></span></article><article><CalendarClock/><span>调度计划<strong>{{summary?.schedules}}</strong></span></article></div>
  <section class="template-strip"><header><h2>作业模板</h2><span>高风险模板执行前必须由其他管理员审批</span></header><div><article v-for="item in templates" :key="item.id" :class="{disabled:!item.enabled}"><b :data-risk="item.risk">{{item.category}} · {{item.risk}}</b><h3>{{item.name}}</h3><p>{{item.description}}</p><code>{{item.command}}</code><footer><button class="subtle" @click="toggle(item)">{{item.enabled?'停用':'启用'}}</button><button :disabled="!item.enabled" @click="openExecution(item)"><Play/>选择目标</button></footer></article></div></section>
  <section class="playbook-strip"><header><div><h2>Playbook 剧本</h2><span>定义常量、默认变量和命令内容，执行前由管理员审批</span></div><button @click="openCreatePlaybook"><FilePlus2/>新建 Playbook</button></header><div><article v-for="item in playbooks" :key="item.id" :class="{disabled:!item.enabled}"><b>Playbook · {{Object.keys(item.variables).length}} 个变量</b><h3>{{item.name}}</h3><p>{{item.description||'暂无描述'}}</p><code>{{item.content}}</code><footer><button class="subtle" @click="editPlaybook(item)">编辑</button><button class="subtle" @click="togglePlaybookItem(item)">{{item.enabled?'停用':'启用'}}</button><button :disabled="!item.enabled" @click="openPlaybookExecution(item)"><Play/>选择目标</button><button class="subtle" @click="removePlaybookItem(item)">删除</button></footer></article><div v-if="!playbooks.length" class="schedule-empty">暂无 Playbook，请先创建剧本</div></div></section>
  <div class="jobs-workspace"><main><nav><button :class="{active:tab==='executions'}" @click="tab='executions'">执行记录</button><button :class="{active:tab==='schedules'}" @click="tab='schedules'">调度计划</button></nav><template v-if="tab==='executions'"><button v-for="job in jobs" :key="job.id" class="job-entry" :class="{selected:selected?.id===job.id}" @click="selected=job"><b :data-status="job.status">{{statusLabel(job.status)}}</b><div><strong>{{job.name}}</strong><span>{{job.targets.join('、')}} · {{job.operator}}</span></div><div class="entry-progress"><i :data-tone="progressTone(job.status)" :style="{width:job.progress+'%'}"></i></div><em>{{job.progress}}%</em><time>{{job.startedAt.slice(11)}}</time></button></template><template v-else><div class="schedule-toolbar"><div><strong>调度计划</strong><span>按 Cron 自动创建并执行任务，高风险模板仍进入审批</span></div><button @click="openCreateSchedule"><CalendarPlus/>新建计划</button></div><article v-for="schedule in schedules" :key="schedule.id" class="schedule-entry" :class="{disabled:!schedule.enabled}"><CalendarClock/><div><strong>{{schedule.name}}</strong><span>{{schedule.templateName||schedule.templateId}} · {{schedule.cron}} · {{schedule.targets.length}} 台目标</span><small v-if="schedule.lastRun">上次 {{schedule.lastRun}} · {{schedule.lastStatus||'--'}}</small></div><time>{{schedule.enabled?`下次 ${schedule.nextRun||'待计算'}`:'已停用'}}</time><b :data-enabled="schedule.enabled">{{schedule.enabled?'已启用':'已停用'}}</b><div class="schedule-actions"><button @click="runScheduleNow(schedule)"><Zap/>立即执行</button><button @click="openEditSchedule(schedule)"><Pencil/>编辑</button><button @click="toggleScheduleItem(schedule)">{{schedule.enabled?'停用':'启用'}}</button><button @click="removeScheduleItem(schedule)"><Trash2/>删除</button></div></article><div v-if="!schedules.length" class="schedule-empty">暂无调度计划，请先创建作业模板和目标资产</div></template></main>
    <aside class="job-console"><template v-if="selected"><header><div><span>EXECUTION LOG</span><h2>{{selected.name}}</h2></div><Terminal/></header><div class="console-meta"><span>{{selected.id}}</span><span>第 {{selected.attempt}} 次</span><b :data-status="selected.status">{{statusLabel(selected.status)}}</b></div><div class="approval-note" v-if="selected.status==='awaiting_approval'">高风险任务等待审批，申请人 {{selected.operator}} 不能自审。</div><div class="log-stream"><p v-for="log in selected.logs" :key="log.time+log.message" :data-level="log.level"><time>{{log.time}}</time><b>[{{log.level}}]</b>{{log.message}}</p></div><footer><button v-if="selected.status==='awaiting_approval'" @click="action(selected,'approve')"><ShieldCheck/>审批通过</button><button v-if="selected.status==='pending'" @click="action(selected,'run')"><Play/>开始执行</button><button v-if="selected.status==='running'" @click="action(selected,'cancel')"><Square/>取消执行</button><button v-if="selected.status==='failed'||selected.status==='cancelled'" @click="action(selected,'retry')"><RotateCcw/>重新执行</button></footer></template><div v-else class="empty-console"><ScrollText/><strong>选择执行记录</strong><span>查看实时输出与审计日志</span></div></aside>
  </div>
  <div v-if="showTemplate" class="job-modal" @click.self="showTemplate=false"><form @submit.prevent="submitTemplate"><header><h2>新建作业模板</h2><button type="button" @click="showTemplate=false"><X/></button></header><label>模板名称<input v-model="templateForm.name" required maxlength="80"></label><label>分类<input v-model="templateForm.category" required maxlength="30"></label><label>描述<textarea v-model="templateForm.description" maxlength="300"></textarea></label><label>受控命令<input v-model="templateForm.command" required maxlength="500" placeholder="例如 health-check --full"></label><label>风险等级<select v-model="templateForm.risk"><option value="low">低风险</option><option value="medium">中风险</option><option value="high">高风险（需要审批）</option></select></label><footer><button type="button" @click="showTemplate=false">取消</button><button>保存模板</button></footer></form></div>
  <div v-if="showExecute&&activeTemplate" class="job-modal" @click.self="showExecute=false"><form class="target-dialog" @submit.prevent="submitExecution"><header><div><small>CREATE EXECUTION</small><h2>{{activeTemplate.name}}</h2></div><button type="button" @click="showExecute=false"><X/></button></header><label>执行超时（秒）<input v-model.number="timeoutSeconds" type="number" min="10" max="86400"></label><h3>选择CMDB目标资产 <span>已选 {{selectedTargets.length}} 台</span></h3><div class="target-list"><label v-for="asset in onlineAssets" :key="asset.id"><input v-model="selectedTargets" type="checkbox" :value="asset.id"><div><strong>{{asset.name}}</strong><span>{{asset.ip||asset.id}} · {{asset.environment}} · {{asset.projectGroup}}</span></div><b>{{asset.status}}</b></label></div><footer><button type="button" @click="showExecute=false">取消</button><button :disabled="!selectedTargets.length"><Play/>创建并执行</button></footer></form></div>
  <div v-if="showSchedule" class="job-modal" @click.self="showSchedule=false"><form class="schedule-dialog" @submit.prevent="submitSchedule"><header><div><small>SCHEDULE CONTROL</small><h2>{{editingSchedule?'编辑调度计划':'新建调度计划'}}</h2></div><button type="button" @click="showSchedule=false"><X/></button></header><label>计划名称<input v-model="scheduleForm.name" required maxlength="80" placeholder="例如 每日凌晨主机巡检"></label><label>作业模板<select v-model="scheduleForm.templateId" required><option value="" disabled>请选择模板</option><option v-for="item in templates.filter(value=>value.enabled)" :key="item.id" :value="item.id">{{item.name}} · {{item.risk}}</option></select></label><label>执行周期（Cron）<input v-model="scheduleForm.cron" required placeholder="0 2 * * *"></label><div class="cron-presets"><button v-for="preset in cronPresets" :key="preset.value" type="button" :class="{active:scheduleForm.cron===preset.value}" @click="scheduleForm.cron=preset.value">{{preset.label}}</button></div><label>执行超时（秒）<input v-model.number="scheduleForm.timeoutSeconds" type="number" min="10" max="86400"></label><label class="schedule-enabled"><input v-model="scheduleForm.enabled" type="checkbox"> 创建后立即启用</label><h3>选择CMDB目标资产 <span>已选 {{scheduleForm.targets.length}} 台</span></h3><div class="target-list"><label v-for="asset in onlineAssets" :key="asset.id"><input v-model="scheduleForm.targets" type="checkbox" :value="asset.id"><div><strong>{{asset.name}}</strong><span>{{asset.ip||asset.id}} · {{asset.environment}} · {{asset.projectGroup}}</span></div><b>{{asset.status}}</b></label></div><footer><button type="button" @click="showSchedule=false">取消</button><button :disabled="scheduleSaving"><CalendarPlus/>{{scheduleSaving?'保存中':'保存计划'}}</button></footer></form></div>
  <div v-if="showPlaybook" class="job-modal" @click.self="showPlaybook=false"><form class="playbook-dialog" @submit.prevent="submitPlaybook"><header><div><small>PLAYBOOK EDITOR</small><h2>{{editingPlaybook?'编辑 Playbook':'新建 Playbook'}}</h2></div><button type="button" @click="showPlaybook=false"><X/></button></header><label>名称<input v-model="playbookForm.name" required maxlength="80"></label><label>描述<textarea v-model="playbookForm.description" rows="2" maxlength="500"></textarea></label><label>剧本内容<textarea v-model="playbookForm.content" rows="8" required placeholder="echo {{message}}" class="code-input"></textarea></label><label>常量（每行 KEY=值，运行时不可覆盖）<textarea v-model="constantsText" rows="4" placeholder="region=shanghai"></textarea></label><label>变量（每行 KEY=默认值，运行时可以覆盖）<textarea v-model="variablesText" rows="4" placeholder="message=hello"></textarea></label><label class="schedule-enabled"><input v-model="playbookForm.enabled" type="checkbox"> 启用 Playbook</label><footer><button type="button" @click="showPlaybook=false">取消</button><button :disabled="playbookSaving">{{playbookSaving?'保存中':'保存 Playbook'}}</button></footer></form></div>
</section></template>
