<template><div class="k8s-browser"><aside class="k8s-tree"><header><strong>K8s 集群</strong><span>{{inventory?.clusters?.length||0}}</span></header><button v-for="cluster in inventory?.clusters||[]" :key="cluster.id" :class="{active:selectedCluster?.id===cluster.id}" @click="selectCluster(cluster)"><Boxes/><div><strong>{{cluster.name}}</strong><span>{{cluster.namespaceCount}} 个命名空间 · {{cluster.version||'-'}}</span></div></button><button class="cluster-resource" :class="{active:namespace==='__cluster__'}" :disabled="!selectedCluster" @click="selectNamespace('__cluster__')"><Layers/>集群级资源</button></aside><main class="k8s-content"><header><div><span>KUBERNETES ASSET EXPLORER</span><h2>{{selectedCluster?.name||'请选择集群'}}</h2><p v-if="selectedCluster">{{namespace==='__cluster__'?'集群级资源':namespace}} · {{visibleResources.length}} 个资源</p></div><input v-model="query" placeholder="搜索资源名称 / 类型"></header><div v-if="namespace!=='__cluster__'" class="namespace-strip"><button v-for="item in selectedCluster?.namespaces||[]" :key="item.id" :class="{active:namespace===item.name}" @click="selectNamespace(item.name)">{{item.name}}<b>{{resourceTotal(item.counts)}}</b></button></div><div v-if="selectedCluster" class="k8s-resource-groups"><section v-for="group in groups" :key="group.type"><header><component :is="groupIcon(group.type)"/><strong>{{group.label}}</strong><b>{{group.items.length}}</b></header><div class="k8s-resource-grid"><button v-for="asset in group.items" :key="asset.id" @click="emit('select',asset.id)"><div><strong>{{asset.name}}</strong><span>{{asset.typeName}} · {{asset.status}}</span></div><small>{{asset.ip||asset.location||'—'}}</small></button><p v-if="!group.items.length">暂无资源</p></div></section></div><div v-else class="empty-cluster"><Boxes/><strong>选择一个 K8s 集群</strong><span>按命名空间查看 Pod、Service、Workload、存储和 Ingress</span></div></main></div></template>

<script setup lang="ts">
import { computed,onMounted,ref,type Component } from 'vue'
import { Activity, Boxes, Database, GitFork, Layers, Network, Server, ShieldCheck } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/useAuthStore'
import type { Asset } from '@/features/cmdb/types'
type Namespace={id:string;name:string;status:string;counts:Record<string,number>;resources:Asset[]};type Cluster={id:string;name:string;status:string;version?:string;namespaceCount:number;counts:Record<string,number>;namespaces:Namespace[];clusterResources:Asset[]};type Inventory={clusters:Cluster[]}
const emit=defineEmits<{(event:'select',id:string):void}>();const auth=useAuthStore(),inventory=ref<Inventory>(),selectedCluster=ref<Cluster>(),namespace=ref('__cluster__'),query=ref(''),error=ref('')
const visibleResources=computed(()=>{const source=namespace.value==='__cluster__'?(selectedCluster.value?.clusterResources||[]):(selectedCluster.value?.namespaces.find(n=>n.name===namespace.value)?.resources||[]);const q=query.value.trim().toLowerCase();return source.filter(a=>!q||(a.name+' '+a.type+' '+a.typeName+' '+a.ip).toLowerCase().includes(q))})
const groups=computed(()=>{const labels:Record<string,string>={workload:'工作负载',pod:'Pod',service:'Service',pvc:'存储 PVC',ingress:'Ingress',node:'节点',pv:'持久卷 PV',storageclass:'存储类'};return Object.entries(labels).map(([type,label])=>({type,label,items:visibleResources.value.filter(a=>a.type==='k8s-'+type)}))})
function resourceTotal(counts:Record<string,number>){return Object.values(counts||{}).reduce((a,b)=>a+b,0)}
function selectCluster(cluster:Cluster){selectedCluster.value=cluster;namespace.value=cluster.namespaces[0]?.name||'__cluster__'}
function selectNamespace(name:string){namespace.value=name}
function groupIcon(type:string):Component{return ({workload:Layers,pod:Boxes,service:Network,pvc:Database,ingress:GitFork,node:Server,pv:Database,storageclass:ShieldCheck} as Record<string,Component>)[type]||Activity}
async function load(){try{const response=await fetch('/api/v1/cmdb/kubernetes',{headers:{Authorization:`Bearer ${auth.token}`}});if(!response.ok)throw new Error(`请求失败 (${response.status})`);inventory.value=await response.json() as Inventory;if(inventory.value.clusters.length)selectCluster(inventory.value.clusters[0])}catch(reason){error.value=reason instanceof Error?reason.message:'K8s 资产加载失败'}}
onMounted(load)
</script>

<style scoped>
.k8s-browser{display:grid;grid-template-columns:270px minmax(0,1fr);min-height:640px;border:1px solid #24314d;border-radius:12px;overflow:hidden;background:#081522}.k8s-tree{padding:12px;border-right:1px solid #24314d;background:#0b1a29}.k8s-tree>header,.k8s-content>header{display:flex;align-items:center;justify-content:space-between;gap:12px}.k8s-tree>header{padding:8px 10px}.k8s-tree>header span{color:#6f91a5}.k8s-tree>button{width:100%;display:flex;align-items:center;gap:10px;margin-top:8px;padding:11px;text-align:left}.k8s-tree>button div{display:flex;flex-direction:column}.k8s-tree>button span{font-size:11px;color:#6f91a5}.k8s-tree>button.active{border-color:#16b8e4;background:#0c4967}.cluster-resource{margin-top:14px!important}.k8s-content{min-width:0;padding:20px}.k8s-content>header input{max-width:280px}.k8s-content>header span{color:#22d3ee;font-size:11px;letter-spacing:.14em}.k8s-content h2{margin:6px 0}.k8s-content p{margin:0;color:#6f91a5}.namespace-strip{display:flex;gap:7px;overflow:auto;padding:17px 0}.namespace-strip button{white-space:nowrap}.namespace-strip b{margin-left:6px;color:#22d3ee}.k8s-resource-groups{display:grid;gap:14px}.k8s-resource-groups>section{border:1px solid #18384a;border-radius:10px;background:#091b29}.k8s-resource-groups>section>header{display:flex;align-items:center;gap:8px;padding:12px 14px;border-bottom:1px solid #123043}.k8s-resource-groups>section>header svg{color:#22d3ee}.k8s-resource-groups>section>header b{margin-left:auto;color:#7890aa}.k8s-resource-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(210px,1fr));gap:9px;padding:12px}.k8s-resource-grid button{display:flex;justify-content:space-between;align-items:center;text-align:left;min-width:0}.k8s-resource-grid span,.k8s-resource-grid small{display:block;color:#6f91a5;font-size:11px}.k8s-resource-grid p{grid-column:1/-1;color:#64748b;padding:8px}.empty-cluster{min-height:460px;display:flex;flex-direction:column;align-items:center;justify-content:center;color:#6f91a5}.empty-cluster svg{width:44px;height:44px;color:#22d3ee}.empty-cluster strong{color:#dcecff;margin-top:12px}@media(max-width:900px){.k8s-browser{grid-template-columns:1fr}.k8s-tree{border-right:0;border-bottom:1px solid #24314d}.k8s-content>header{flex-direction:column;align-items:flex-start}.k8s-content>header input{max-width:none;width:100%}}
</style>
