<template><section class="discovery-panel k8s-panel"><header><div><h2>Kubernetes 资源采集</h2><span>通过集群内只读 ServiceAccount 同步 Cluster、Node、Namespace、Workload、Pod、Service、Ingress</span></div><button @click="load"><RefreshCw :class="{spin:loading}"/>刷新状态</button></header><div class="k8s-status"><article><Boxes/><div><span>采集器状态</span><strong>{{status?.ready?'可用':'不可用'}}</strong></div></article><article><Server/><div><span>集群</span><strong>{{status?.clusterName||'-'}}</strong></div></article><article><Boxes/><div><span>Kubernetes 版本</span><strong>{{status?.version||'-'}}</strong></div></article><article><Clock3/><div><span>最近同步</span><strong>{{status?.lastSync||'尚未同步'}}</strong></div></article></div><div v-if="status?.message" class="discovery-error">{{status.message}}</div><div class="k8s-action"><div><ShieldCheck/><strong>只读采集</strong><span>不会修改、删除或重启任何 Kubernetes 资源</span></div><button class="primary" :disabled="syncing||!status?.ready" @click="sync">{{syncing?'同步中...':'立即同步到 CMDB'}}</button></div><div v-if="error" class="discovery-error">{{error}}</div><div v-if="result" class="k8s-result"><div class="k8s-summary"><span>总计 <strong>{{result.total}}</strong></span><span>新增 <strong>{{result.created}}</strong></span><span>更新 <strong>{{result.updated}}</strong></span><span>未变化 <strong>{{result.unchanged}}</strong></span><span>失败 <strong>{{result.failed}}</strong></span></div><div class="k8s-counts"><article v-for="(count,kind) in result.counts" :key="kind"><span>{{kind}}</span><strong>{{count}}</strong></article></div><div v-if="result.errors?.length" class="k8s-errors"><p v-for="item in result.errors" :key="item">{{item}}</p></div></div></section></template>

<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { Boxes, Clock3, RefreshCw, Server, ShieldCheck } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/useAuthStore'
type Status={configured:boolean;ready:boolean;clusterName?:string;apiServer?:string;version?:string;lastSync?:string;message?:string};type Result={startedAt:string;finishedAt:string;total:number;created:number;updated:number;unchanged:number;failed:number;counts:Record<string,number>;errors?:string[]}
const auth=useAuthStore(),status=ref<Status>(),result=ref<Result>(),loading=ref(false),syncing=ref(false),error=ref('');const headers=computed(()=>({Authorization:`Bearer ${auth.token}`,'Content-Type':'application/json'}))
async function request<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:headers.value});if(!response.ok){let message=`请求失败 (${response.status})`;try{const body=await response.json() as {message?:string};message=body.message||message}catch{}throw new Error(message)}return response.json() as Promise<T>}
async function load(){loading.value=true;error.value='';try{status.value=await request<Status>('/api/v1/k8s/status')}catch(reason){error.value=reason instanceof Error?reason.message:'Kubernetes 状态读取失败'}finally{loading.value=false}}
async function sync(){syncing.value=true;error.value='';try{result.value=await request<Result>('/api/v1/k8s/sync',{method:'POST'});await load()}catch(reason){error.value=reason instanceof Error?reason.message:'Kubernetes 同步失败'}finally{syncing.value=false}}
onMounted(load)
</script>

<style scoped>
.k8s-status{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;padding:18px 20px}.k8s-status article{display:flex;align-items:center;gap:12px;padding:15px;border:1px solid #18384a;border-radius:10px;background:#091b29}.k8s-status svg{color:#22d3ee}.k8s-status span{display:block;color:#7890aa;font-size:12px}.k8s-status strong{font-size:16px}.k8s-action{display:flex;align-items:center;justify-content:space-between;gap:16px;margin:0 20px 18px;padding:14px 16px;border:1px solid #155e75;border-radius:10px;background:#082b38}.k8s-action>div{display:grid;grid-template-columns:auto 1fr;gap:2px 9px;align-items:center;color:#a5f3fc}.k8s-action svg{grid-row:1/3}.k8s-action span{color:#7dd3fc}.k8s-result{padding:0 20px 20px}.k8s-summary{display:flex;gap:24px;padding:14px;border:1px solid #18384a;border-radius:10px;background:#091b29}.k8s-summary span{color:#7890aa}.k8s-summary strong{color:#e5f4ff;margin-left:5px}.k8s-counts{display:grid;grid-template-columns:repeat(auto-fit,minmax(150px,1fr));gap:10px;margin-top:12px}.k8s-counts article{display:flex;justify-content:space-between;padding:12px;border:1px solid #18384a;border-radius:8px;background:#081a27}.k8s-errors{margin-top:12px;color:#fda4af}.k8s-errors p{margin:4px 0}.k8s-panel{grid-column:1/-1}@media(max-width:900px){.k8s-status{grid-template-columns:1fr 1fr}.k8s-action{align-items:flex-start;flex-direction:column}.k8s-summary{flex-wrap:wrap}}
</style>
