<script setup lang="ts">
import{ref}from'vue';import{Plus,Trash2,X}from'lucide-vue-next';import{createModel,toggleModel,updateModel}from'@/api/cmdb';import{useAuthStore}from'@/stores/useAuthStore';import type{CiModel,ModelField}from'@/features/cmdb/types'
const props=defineProps<{models:CiModel[]}>(),emit=defineEmits<{close:[];changed:[]}>(),auth=useAuthStore(),editing=ref<CiModel>(),error=ref('')
const blank=():CiModel=>({code:'',name:'',category:'计算',icon:'Box',count:0,description:'',enabled:true,fields:[]});const form=ref<CiModel>(blank())
function edit(item?:CiModel){editing.value=item;form.value=item?structuredClone(item):blank()}
function addField(){form.value.fields.push({name:'',label:'',type:'text',required:false,defaultValue:'',options:[]})}
function setOptions(field:ModelField,event:Event){field.options=(event.target as HTMLInputElement).value.split(',').map(v=>v.trim()).filter(Boolean)}
function optText(field:ModelField){return (field.options??[]).join(',')}
async function save(){error.value='';try{const input={code:form.value.code,name:form.value.name,category:form.value.category,icon:form.value.icon,description:form.value.description,fields:form.value.fields};if(editing.value)await updateModel(auth.token,editing.value.code,input);else await createModel(auth.token,input);editing.value=undefined;form.value=blank();emit('changed')}catch(e){error.value=e instanceof Error?e.message:'保存失败'}}
async function toggle(item:CiModel){try{await toggleModel(auth.token,item.code);emit('changed')}catch(e){error.value=e instanceof Error?e.message:'操作失败'}}
</script>
<template><div class="model-modal" @click.self="emit('close')"><section><header><div><small>CI MODEL DESIGNER</small><h2>CI模型管理</h2></div><button @click="emit('close')"><X/></button></header><div class="model-manager"><aside><button class="new-model" @click="edit()"><Plus/>新建模型</button><article v-for="item in props.models" :key="item.code" :class="{disabled:!item.enabled}"><button @click="edit(item)"><strong>{{item.name}}</strong><span>{{item.code}} · {{(item.fields||[]).length}} 个字段</span></button><button @click="toggle(item)">{{item.enabled?'停用':'启用'}}</button></article></aside><form @submit.prevent="save"><p v-if="error" class="cmdb-error">{{error}}</p><label>模型编码<input v-model="form.code" required pattern="[a-z0-9-]+" :disabled="!!editing" placeholder="例如 linux-server"></label><label>模型名称<input v-model="form.name" required></label><div class="model-row"><label>分类<input v-model="form.category" required></label><label>图标<input v-model="form.icon"></label></div><label>说明<textarea v-model="form.description"></textarea></label><header><h3>动态属性字段</h3><button type="button" @click="addField"><Plus/>添加字段</button></header><div class="field-row" v-for="(field,index) in form.fields" :key="index"><input v-model="field.name" required placeholder="字段编码"><input v-model="field.label" required placeholder="显示名称"><select v-model="field.type"><option value="text">文本</option><option value="number">数字</option><option value="boolean">布尔</option><option value="date">日期</option><option value="select">选项</option></select><input v-if="field.type==='select'" :value="optText(field)" @change="setOptions(field,$event)" placeholder="选项，逗号分隔"><label><input v-model="field.required" type="checkbox">必填</label><button type="button" @click="form.fields.splice(index,1)"><Trash2/></button></div><footer><button type="button" @click="form=blank();editing=undefined">重置</button><button class="primary">{{editing?'保存修改':'创建模型'}}</button></footer></form></div></section></div></template>
