<script setup lang="ts">
import {computed,ref} from 'vue'
import {ExternalLink,X,SquareTerminal} from 'lucide-vue-next'
import {useRouter} from 'vue-router'
import type {CoverageHost,MonitorCoverage} from '@/api/monitor'
import {installHostExporter} from '@/api/monitor'
import {useAuthStore} from '@/stores/useAuthStore'
const props=defineProps<{coverage:MonitorCoverage}>()
const router=useRouter(),auth=useAuthStore(),environment=ref(''),status=ref('problem'),guide=ref<CoverageHost>(),installing=ref(''),installError=ref('')
const commands='mkdir -p /opt/cmdb/node-exporter\ncd /opt/cmdb/node-exporter\ndocker compose up -d\ncurl -fsS http://127.0.0.1:9100/metrics >/dev/null'
const environments=computed(()=>[...new Set(props.coverage.hosts.map(item=>item.environment).filter(Boolean))])
const hosts=computed(()=>props.coverage.hosts.filter(item=>(!environment.value||item.environment===environment.value)&&(status.value==='all'||status.value==='problem'&&item.monitorStatus!=='healthy'||item.monitorStatus===status.value)))
function openAsset(id:string){void router.push({path:'/cmdb',query:{asset:id}})}
async function install(host:CoverageHost){if(!window.confirm(`确认通过Ansible Runner在 ${host.name} 安装Node Exporter？`))return;installing.value=host.assetId;installError.value='';try{const job=await installHostExporter(auth.token,host.assetId);void router.push({path:'/jobs',query:{job:job.id}})}catch(reason){installError.value=reason instanceof Error?reason.message:'安装任务创建失败'}finally{installing.value=''}}
</script>
<template><section class="coverage-panel"><header><div><span>CMDB MONITORING COVERAGE</span><h2>主机监控覆盖率</h2></div><strong>{{coverage.percentage}}%</strong></header><div class="coverage-stats"><article><span>Agent资产</span><b>{{coverage.total}}</b></article><article><span>已接入</span><b>{{coverage.monitored}}</b></article><article><span>采集正常</span><b>{{coverage.healthy}}</b></article><article data-tone="danger"><span>采集异常</span><b>{{coverage.down}}</b></article><article data-tone="warning"><span>未接入</span><b>{{coverage.missing}}</b></article></div><div class="coverage-bar"><i :style="{width:coverage.percentage+'%'}"></i></div><div v-if="!coverage.available" class="coverage-notice">Prometheus当前不可用，以下资产暂按未接入显示</div><div v-if="installError" class="coverage-notice">{{installError}}</div><div class="coverage-filters"><select v-model="environment"><option value="">全部环境</option><option v-for="item in environments" :key="item">{{item}}</option></select><select v-model="status"><option value="problem">仅看问题</option><option value="all">全部主机</option><option value="healthy">采集正常</option><option value="down">采集异常</option><option value="missing">未接入</option></select><span>{{hosts.length}} 台主机</span></div><div class="coverage-hosts"><article v-for="host in hosts" :key="host.assetId"><button class="coverage-asset" @click="openAsset(host.assetId)"><strong>{{host.name}}</strong><small>{{host.assetId}} · {{host.ip||'无IP'}}</small></button><span>{{host.environment}}</span><span>{{host.projectGroup}}</span><b :data-status="host.monitorStatus">{{host.monitorStatus==='healthy'?'采集正常':host.monitorStatus==='down'?'采集异常':'未接入'}}</b><button v-if="host.monitorStatus==='missing'" title="查看安装指引" @click="guide=host"><SquareTerminal/></button><button v-if="host.monitorStatus==='missing'&&auth.user?.permissions.includes('job:manage')" :disabled="installing===host.assetId" title="自动安装" @click="install(host)">{{installing===host.assetId?'…':'安装'}}</button><button title="打开CMDB资产" @click="openAsset(host.assetId)"><ExternalLink/></button></article><div v-if="!hosts.length" class="coverage-empty">当前筛选条件下没有主机</div></div><div v-if="guide" class="coverage-guide-backdrop" @click.self="guide=undefined"><aside class="coverage-guide"><header><div><span>NODE EXPORTER SETUP</span><h3>{{guide.name}}</h3><small>{{guide.ip}}</small></div><button @click="guide=undefined"><X/></button></header><p>在目标Linux主机上传项目中的 node-exporter-compose.yml，然后执行：</p><pre>{{commands}}</pre><p>确认Prometheus服务器可以访问 <code>{{guide.ip}}:9100</code>。服务发现最多30秒后自动更新，无需重启Gateway。</p></aside></div></section></template>
