<script setup lang="ts">
import { computed, onBeforeUnmount, onMounted, ref } from 'vue'
import { CheckCircle2, Clock3, RefreshCw, ShieldCheck, Terminal, XCircle } from 'lucide-vue-next'
import { listCredentials, type Credential } from '@/api/cmdb'
import { useAuthStore } from '@/stores/useAuthStore'

type Operation={id:string;name:string;description:string;command:string;risk:string}
type TargetResult={target:string;status:string;output?:string;error?:string;duration?:string}
type Execution={id:string;operationId:string;operationName:string;targets:string[];status:string;requestedBy:string;approvedBy?:string;createdAt:string;finishedAt?:string;results:TargetResult[]}
const auth=useAuthStore(),operations=ref<Operation[]>([]),executions=ref<Execution[]>([]),credentials=ref<Credential[]>([]),operationId=ref('uptime'),targets=ref('172.28.69.161'),credentialId=ref(''),busy=ref(false),error=ref(''),message=ref('')
const headers=computed(()=>({Authorization:`Bearer ${auth.token}`,'Content-Type':'application/json'}))
const sshCredentials=computed(()=>credentials.value.filter(item=>item.kind==='ssh'))
async function request<T>(url:string,options?:RequestInit){const response=await fetch(url,{...options,headers:headers.value});if(!response.ok){let detail=`请求失败 (${response.status})`;try{const body=await response.json() as {message?:string};detail=body.message||detail}catch{}throw new Error(detail)}return response.json() as Promise<T>}
async function load(){try{[operations.value,executions.value,credentials.value]=await Promise.all([request<Operation[]>('/api/v1/discovery/remote-operations'),request<Execution[]>('/api/v1/discovery/remote-executions'),listCredentials(auth.token)]);error.value=''}catch(reason){error.value=reason instanceof Error?reason.message:'远程执行数据加载失败'}}
async function submit(){busy.value=true;error.value='';message.value='';try{const hosts=targets.value.split(/\r?\n/).map(value=>value.trim()).filter(Boolean);const execution=await request<Execution>('/api/v1/discovery/remote-executions',{method:'POST',body:JSON.stringify({operationId:operationId.value,targets:hosts,credentialId:credentialId.value})});message.value=`${execution.id} 已提交，等待审批后执行`;await load()}catch(reason){error.value=reason instanceof Error?reason.message:'提交失败'}finally{busy.value=false}}
async function approve(id:string){busy.value=true;error.value='';try{await request(`/api/v1/discovery/remote-executions/${encodeURIComponent(id)}/approve`,{method:'POST'});message.value=`${id} 已审批并开始执行`;await load()}catch(reason){error.value=reason instanceof Error?reason.message:'审批失败'}finally{busy.value=false}}
function statusLabel(status:string){return {awaiting_approval:'待审批',running:'执行中',success:'成功',partial:'部分成功',failed:'失败'}[status]||status}
let timer:ReturnType<typeof setInterval>|undefined
onMounted(()=>{load();timer=setInterval(()=>{if(executions.value.some(item=>item.status==='running'))load()},3000)});onBeforeUnmount(()=>{if(timer)clearInterval(timer)})
</script>

<template><section class="discovery-panel remote-execution"><header><div><h2>受控批量远程执行</h2><span>仅允许服务端预定义只读命令；提交后必须审批，逐台记录 SSH 输出</span></div><button @click="load"><RefreshCw :class="{spin:busy}"/></button></header><div class="remote-safety"><ShieldCheck/><span><strong>安全白名单已启用</strong>：不接受任意 Shell 命令，不修改目标系统状态。</span></div><div class="scanner-form remote-form"><label><span>只读操作</span><select v-model="operationId"><option v-for="operation in operations" :key="operation.id" :value="operation.id">{{operation.name}} · {{operation.description}}</option></select></label><label><span>目标主机（每行一个 IP/主机名，最多 20 台）</span><textarea v-model="targets" rows="4"></textarea></label><label><span>SSH 凭据</span><select v-model="credentialId"><option value="">使用服务端默认</option><option v-for="credential in sshCredentials" :key="credential.id" :value="credential.id">{{credential.name}} ({{credential.username||'-'}})</option></select></label><button class="primary" :disabled="busy" @click="submit">提交审批</button></div><div v-if="message" class="scanner-result">{{message}}</div><div v-if="error" class="discovery-error remote-error">{{error}}</div><div class="remote-history"><article v-for="execution in executions.slice(0,8)" :key="execution.id"><header><div><Terminal/><strong>{{execution.operationName}}</strong><span>{{execution.createdAt}} · {{execution.targets.length}} 台 · {{execution.requestedBy}}</span></div><b :data-status="execution.status">{{statusLabel(execution.status)}}</b></header><div class="remote-targets"><span v-for="target in execution.targets" :key="target">{{target}}</span></div><div v-if="execution.status==='awaiting_approval'" class="remote-actions"><Clock3/><span>等待管理员审批</span><button class="primary" :disabled="busy" @click="approve(execution.id)">审批并执行</button></div><details v-else><summary>查看逐台执行结果</summary><div class="remote-results"><article v-for="result in execution.results" :key="result.target"><span><CheckCircle2 v-if="result.status==='success'"/><XCircle v-else/><b>{{result.target}}</b><small>{{result.duration||statusLabel(result.status)}}</small></span><pre v-if="result.output">{{result.output}}</pre><p v-if="result.error">{{result.error}}</p></article></div></details></article><div v-if="!executions.length" class="remote-empty">暂无远程执行记录</div></div></section></template>

<style scoped>
.remote-safety{display:flex;align-items:center;gap:10px;margin:0 20px 16px;padding:12px 14px;border:1px solid #155e75;border-radius:10px;background:#082b38;color:#a5f3fc}.remote-safety svg{flex:none}.remote-form select{min-width:260px}.remote-error{margin:0 20px 14px}.remote-history{display:grid;gap:12px;padding:0 20px 20px}.remote-history>article{border:1px solid #18384a;border-radius:12px;background:#081a27;overflow:hidden}.remote-history>article>header{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:13px 15px;border-bottom:1px solid #123043}.remote-history>article>header>div{display:grid;grid-template-columns:auto 1fr;gap:2px 9px;align-items:center}.remote-history>article>header svg{grid-row:1/3;color:#22d3ee}.remote-history>article>header span{color:#6f91a5;font-size:12px}.remote-history b{font-size:12px}.remote-history b[data-status=awaiting_approval]{color:#f59e0b}.remote-history b[data-status=running]{color:#38bdf8}.remote-history b[data-status=success]{color:#2dd4bf}.remote-history b[data-status=partial]{color:#f59e0b}.remote-history b[data-status=failed]{color:#fb7185}.remote-targets{display:flex;flex-wrap:wrap;gap:6px;padding:11px 15px}.remote-targets span{padding:4px 8px;border-radius:6px;background:#0d2a3b;color:#9bdffc;font-family:monospace;font-size:12px}.remote-actions{display:flex;align-items:center;gap:9px;padding:0 15px 14px;color:#f59e0b}.remote-actions button{margin-left:auto}.remote-history details summary{cursor:pointer;padding:11px 15px;border-top:1px solid #123043;color:#7dd3fc}.remote-results{padding:0 15px 15px}.remote-results>article{padding:10px 0;border-top:1px solid #123043}.remote-results>article>span{display:flex;align-items:center;gap:7px}.remote-results small{color:#6f91a5}.remote-results pre{white-space:pre-wrap;margin:8px 0 0;padding:10px;border-radius:8px;background:#020b12;color:#bae6fd;max-height:240px;overflow:auto}.remote-results p{color:#fda4af;margin:8px 0 0}.remote-empty{text-align:center;color:#64869a;padding:30px}
</style>
