<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { Activity, CheckCircle2, RefreshCw, X, XCircle } from 'lucide-vue-next'
import { useAuthStore } from '@/stores/useAuthStore'

type Item = { id:string; name:string; ip:string; type:string; state:string; result?:string; message?:string; updatedAt?:string }
type Event = { id:string; level:string; event:string; message:string; createdAt:string }
type Detail = { task:{id:string;name:string;source:string;status:string;createdAt:string;updatedAt?:string;items:Item[]}; summary:{discovered:number; imported:number; merged:number; pending:number; rejected:number; conflicts:number; failed:number}; events:Event[] }
const props=defineProps<{taskId:string}>(); const emit=defineEmits<{(event:'close'):void}>()
const auth=useAuthStore(),detail=ref<Detail>(),error=ref(''),loading=ref(false)
async function load(){loading.value=true;error.value='';try{const response=await fetch(`/api/v1/discovery/tasks/${encodeURIComponent(props.taskId)}/results`,{headers:{Authorization:`Bearer ${auth.token}`}});if(!response.ok)throw new Error(`请求失败 (${response.status})`);detail.value=await response.json() as Detail}catch(reason){error.value=reason instanceof Error?reason.message:'任务明细加载失败'}finally{loading.value=false}}
onMounted(load)
const stateLabel=(item:Item)=>item.result||item.state||'-'
</script>

<template><div class="modal-backdrop" @click.self="emit('close')"><section class="task-result-modal"><header><div><span>DISCOVERY TASK RESULT</span><h2>{{detail?.task.name||'发现任务结果'}}</h2><p>{{detail?.task.source}} · {{detail?.task.createdAt}}<template v-if="detail?.task.updatedAt"> · 更新 {{detail.task.updatedAt}}</template></p></div><div><button @click="load"><RefreshCw :class="{spin:loading}"/>刷新</button><button class="icon-button" @click="emit('close')"><X/></button></div></header><div v-if="error" class="result-error">{{error}}</div><template v-if="detail"><div class="result-summary"><article><Activity/><span>发现总数<strong>{{detail.summary.discovered}}</strong></span></article><article><CheckCircle2/><span>新入库<strong>{{detail.summary.imported}}</strong></span></article><article><RefreshCw/><span>合并刷新<strong>{{detail.summary.merged}}</strong></span></article><article><span class="pending-dot"></span><span>待审批<strong>{{detail.summary.pending}}</strong></span></article><article><XCircle/><span>失败/冲突<strong>{{detail.summary.failed+detail.summary.conflicts}}</strong></span></article></div><div class="result-columns"><section><h3>资源明细</h3><div class="result-table"><div class="result-row head"><span>资产</span><span>地址</span><span>结果</span><span>说明</span></div><div v-for="item in detail.task.items" :key="item.id" class="result-row"><span><strong>{{item.name}}</strong><small>{{item.id}}</small></span><span>{{item.ip}}<small>{{item.type}}</small></span><span><b :data-state="item.state">{{stateLabel(item)}}</b></span><span>{{item.message||'-'}}<small>{{item.updatedAt||''}}</small></span></div><div v-if="!detail.task.items.length" class="result-empty">暂无发现资源</div></div></section><section><h3>任务日志</h3><div class="result-events"><article v-for="event in detail.events" :key="event.id" :data-level="event.level"><time>{{event.createdAt}}</time><div><strong>{{event.event}}</strong><span>{{event.message}}</span></div></article><div v-if="!detail.events.length" class="result-empty">暂无任务日志</div></div></section></div></template></section></div></template>

<style scoped>
.task-result-modal{width:min(1180px,calc(100vw - 48px));max-height:calc(100vh - 56px);overflow:auto;background:#071522;border:1px solid #1d3d50;border-radius:18px;color:#e5f4ff;box-shadow:0 34px 90px #000b}.task-result-modal>header{display:flex;justify-content:space-between;gap:24px;padding:24px 28px;border-bottom:1px solid #153244}.task-result-modal>header span{color:#22d3ee;font-size:11px;letter-spacing:.16em}.task-result-modal h2{margin:7px 0}.task-result-modal p{margin:0;color:#7594a7}.task-result-modal>header>div:last-child{display:flex;gap:8px}.task-result-modal button{display:flex;align-items:center;gap:6px}.icon-button{padding:8px}.result-summary{display:grid;grid-template-columns:repeat(5,1fr);gap:12px;padding:20px 28px}.result-summary article{display:flex;align-items:center;gap:12px;padding:14px;border:1px solid #18384a;border-radius:12px;background:#091b29}.result-summary svg{color:#22d3ee}.result-summary article span{display:flex;flex-direction:column;color:#7594a7}.result-summary strong{font-size:22px;color:#e5f4ff}.pending-dot{width:10px;height:10px;border-radius:50%;background:#f59e0b}.result-columns{display:grid;grid-template-columns:1.35fr .65fr;gap:20px;padding:0 28px 28px}.result-columns h3{margin:4px 0 12px}.result-table,.result-events{border:1px solid #153244;border-radius:12px;overflow:hidden}.result-row{display:grid;grid-template-columns:1.1fr .8fr .55fr 1.3fr;gap:12px;align-items:center;padding:11px 13px;border-top:1px solid #123043}.result-row.head{border-top:0;color:#6f91a5;background:#081a27;font-size:12px}.result-row span{min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.result-row small{display:block;color:#638296;font-size:11px}.result-row b{font-size:12px}.result-row b[data-state=imported]{color:#2dd4bf}.result-row b[data-state=pending],.result-row b[data-state=conflict]{color:#f59e0b}.result-row b[data-state=failed],.result-row b[data-state=rejected]{color:#fb7185}.result-events article{display:grid;grid-template-columns:150px 1fr;gap:12px;padding:11px 13px;border-top:1px solid #123043}.result-events article:first-child{border-top:0}.result-events time{color:#64869a;font-size:12px}.result-events span{display:block;color:#91adbd;margin-top:3px}.result-events article[data-level=error] strong{color:#fb7185}.result-events article[data-level=warning] strong{color:#f59e0b}.result-empty{text-align:center;color:#64869a;padding:30px}.result-error{margin:18px 28px 0;padding:10px 12px;border-radius:10px;background:#3a111b;color:#fda4af}@media(max-width:900px){.result-summary{grid-template-columns:repeat(2,1fr)}.result-columns{grid-template-columns:1fr}.result-row{grid-template-columns:1fr 1fr}.result-row.head{display:none}}
</style>
